config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  resource :registration
  resource :session
  resource :password_reset
  resource :password

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "main#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  normalizes :email, with: ->(email) {email.strip.downcase} #new method that strips extra spaces, typecharacters and lowercase

  generates_token_for :password_reset, expires_in: 15.minutes do     # :email_confirmation (would be for email confirmation if we would want this functionality)
    password_salt&.last(10)                                          # email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern   # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.


  private

  def authenticate_no_user!
    redirect_to root_path, alert: "You are already logged in, can't proceed action." unless !user_signed_in?
  end

  def authenticate_user!
    redirect_to root_path, alert: "You must be logged in to do that." unless user_signed_in?
  end

  def current_user
    Current.user ||= authenticate_user_from_session
  end
  helper_method :current_user #makes "current_user" avaliable in views

  def authenticate_user_from_session
    User.find_by(id: session[:user_id])
  end

  def user_signed_in?
    current_user.present?
  end

  helper_method :user_signed_in? #makes "user_signed_in?" avaliable in views

  def login(user)
    Current.user = user
    reset_session
    session[:user_id] = user.id
  end

  def logout(user)
    Current.user = nil
    reset_session
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

  before_action :authenticate_no_user!
  before_action :set_user_by_token, only: [:edit, :update]

# READ - form written in views
  def new 
  end

# CREATE - based on the form params
  def create 
    if(user = User.find_by(email: params[:email]))
      PasswordMailer.with(
        user: user,
        token: user.generate_token_for(:password_reset) #That's how to generate the token
      ).password_reset.deliver_later
    end
    redirect_to root_path, notice: "Check your email to reset your password."
  end

#for: when you click the link in the email, use the token and query the user before you do anything
  def edit
    
  end

  def update
    if @user.update(password_params)
      redirect_to new_session_path, notice: "Your password has been reset successfully. Please login."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_token_for(:password_reset, params[:token]) #That's how to take the token and find the user by it
    redirect_to new_password_reset_path, alert: "Invalid token, please try again." unless @user.present?
  end

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

  before_action :authenticate_user!

  def edit

  end

  def update
    if current_user.update(password_params)
      redirect_to edit_password_path, notice: "Your password has been updated succesfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def password_params
    params.require(:user).permit(
      :password,
      :password_confirmation,
      :password_challenge
    ).with_defaults(password_challenge: "")
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(registration_params)
    if @user.save
      login @user
      redirect_to root_path, notice: "Account succesfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  private

  def registration_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    if user = User.authenticate_by(email: params[:email], password: params[:password])
      login user 
      redirect_to root_path, notice: "You have signed in successfully."
    else
      flash[:alert] = "Invalid email or password."
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy
    logout current_user
    redirect_to root_path, notice: "You have been logged out."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Authentication Example" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div> <%= notice %> </div>
    <div> <%= alert %> </div>

    <% if user_signed_in? %>
      <%= link_to "Edit Password", edit_password_path %>
      <%= button_to "Log out", session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_registration_path %>
      <%= link_to "Log in", new_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<h1> Home Page </h1>

app/views/password_resets/edit.html.erb
<h1> Reset your password </h1>

<%= form_with model: @user, url: password_reset_path(token: params[:token]) do |form| %>
  <% if form.object.errors.any? %>
    <% form.object.errors.full_messages.each do |message| %>
    <div> <%= message %> </div>
    <% end %>
  <% end %>

   <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

   <div>
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
  <%= form.submit "Reset your Password" %>
  </div>



<% end %>

app/views/password_resets/new.html.erb
<h1> Reset your password </h1>

<%= form_with model: @user, url: password_reset_path  do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.submit "Reset password" %>
  </div>
<% end %>